blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://github.com/aoneahsan/unified-tracking/tree/main/docs
    about: Check our comprehensive documentation for guides and examples
  - name: 💬 Discussions
    url: https://github.com/aoneahsan/unified-tracking/discussions
    about: Ask questions, share ideas, and discuss with the community
  - name: 📧 Email Support
    url: mailto:aoneahsan@gmail.com
    about: Contact the maintainer directly for sensitive issues or business inquiries
